//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignmentOnResCrud10feb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public int RId { get; set; }
        public string RName { get; set; }
        public string CusineType { get; set; }
    }
}
